fix: add doNotPreventMobileScroll prop to allow for clicks to optionally pass through on mobile
STRML/react-draggable pull request #760
Opened 2024-08-08 19:22 UTC by tnrich

Fixes https://github.com/react-grid-layout/react-draggable/issues/728

@STRML let me know if this PR looks good to you. Thanks!

Add doNotPreventMobileScroll prop to allow for clicks to optionally pass through on mobile

2024-08-08 19:25 UTC, STRML commented
Can you please invert it: "preventMobileScroll", default true.

2024-08-08 19:35 UTC, tnrich commented
What about "allowMobileScroll"? I prefer having the default be false? @STRML

2024-08-09 14:10 UTC, STRML requested changes

2024-08-09 14:10 UTC, STRML commented on lib/DraggableCore.js
> +    if (e.type === 'touchstart' && !this.props.doNotPreventMobileScroll) e.preventDefault();
Still needs change

2024-08-09 16:19 UTC, tnrich commented on lib/DraggableCore.js
> +    if (e.type === 'touchstart' && !this.props.doNotPreventMobileScroll) e.preventDefault();
whoops not sure how that didn't get updated. thanks!

2024-08-10 15:53 UTC, STRML approved these changes

2024-08-10 16:03 UTC, merged

2024-08-10 16:04 UTC, STRML commented
Thanks for the contribution. Please see the additional commit for fixups.

2024-08-12 15:30 UTC, tnrich commented
Thanks @STRML !! Much appreciated 🙏

2024-08-12 15:31 UTC, tnrich commented on specs/draggable.spec.jsx
> +      let pdCalled = false;
nice one @STRML , thanks for adding a test! my Achilles heel!

2024-08-27 17:30 UTC, tnrich commented
@STRML it appears that I need a new release in order to be able to use the updated code. Do you think you could do that plz! 

Thanks! 

![image](https://github.com/user-attachments/assets/0f8b9be1-46f2-4d10-b5c2-81d751912ce6)

2024-09-20 09:35 UTC, taniaprocha commented
When do we have the next release to use this new prop?

2024-12-27 05:34 UTC, consistent-k commented
@STRML @tnrich Which version supports the use of this new prop?

2025-02-13 11:40 UTC, imrahil commented
Any chances to release the new version with this fix?